# 错误处理
## 错误信息增强
上一节我们在处理错误时，使用到了 `createError` 函数。它除了接收文本信息 `message` 外，还包括了请求对象配置 `config`，错误代码 `code`， `xhr` 对象实例 `request` 以及自定义响应对象 `response`。我们来分析一下它的实现:

## createError 

入口文件: `lib/core/createError`
```js
module.exports = function createError(message, config, code, request, response) {
  var error = new Error(message);
  return enhanceError(error, config, code, request, response);
};
```
1、首先实例化 `Error` 类得到 `error` 实例。

2、接着调用 `enhanceError`，并把 `error`、`config`、`code`、`request`、`response` 作为参数传入。

## enhanceError
```js
module.exports = function enhanceError(error, config, code, request, response) {
  error.config = config;
  if (code) {
    error.code = code;
  }

  error.request = request;
  error.response = response;
  error.isAxiosError = true;

  error.toJSON = function() {
    return {
      // Standard
      message: this.message,
      name: this.name,
      // Microsoft
      description: this.description,
      number: this.number,
      // Mozilla
      fileName: this.fileName,
      lineNumber: this.lineNumber,
      columnNumber: this.columnNumber,
      stack: this.stack,
      // Axios
      config: this.config,
      code: this.code
    };
  };
  return error;
};
```
`enhanceError` 接收到用户传递的参数后，将这些参数依次赋值到 `error` 实例上，最后将 `isAxiosError` 置为 `true` 标识是 `axios` 错误，最后返回了 `error`。

## 实际场景使用
```js
axios({
  method: 'get',
  url: '/error/timeout',
  timeout: 2000
}).then((res) => {
  console.log(res)
}).catch((e) => {
  console.log(e.message)
  console.log(e.request)
  console.log(e.code)
})

// xhr 内部抛出超时错误
request.onabort = function handleAbort() {
  ...
  reject(createError('Request aborted', config, 'ECONNABORTED', request))
  ...
}
```
对于应用方来说，他们可以在 `catch` 中捕获到这些错误的详细信息，做进一步的处理。

## 总结
至此我们分析完了 `axios` 中对于错误的增强处理。到此我们已经分析完了 `axios` 的核心功能，下一节我们将来分析 `util` 工具函数。
